IOCProjectMVC/trunk/IOCProjectMVC/IOCProjectMVC/Models/Navbar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IOCProjectMVC.Models
{
    public class Navbar
    {
        public int Id { get; set; }
        public string nameOption { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string area { get; set; }
        public string imageClass { get; set; }
        public string activeli { get; set; }
        public bool status { get; set; }
        public int parentId { get; set; }
        public bool isParent { get; set; }
    }
}

IOCProjectMVC/trunk/IOCProjectMVC/IOCProjectMVC/Controllers/NavbarController.cs
using IOCProjectMVC.Domain;
using IOCProjectMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IOCProjectMVC.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        public ActionResult Index()
        {
            var data = new Data();
            return PartialView("_Navbar", data.navbarItems().ToList());
        }
    }
}

IOCProjectMVC/trunk/IOCProjectMVC/IOCProjectMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>CCLME Data Analytic Viewer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- DataTables CSS -->
    <link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/datatables.net-buttons-bs/css/buttons.bootstrap.min.css")" rel="stylesheet" />
    <!-- DataTables Responsive CSS -->
    <link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />

    <!-- Select2 Responsive CSS -->
    @*<link href="@Url.Content("~/bower_components/select2-bootstrap/select2-bootstrap.css")" rel="stylesheet" type="text/css" />*@
    <link href="@Url.Content("~/bower_components/select2/dist/css/select2.min.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/bower_components/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="@Url.Content("https://js.arcgis.com/3.16/dijit/themes/claro/claro.css")">
    <link rel="stylesheet" href="@Url.Content("https://js.arcgis.com/3.16/esri/css/esri.css")">

    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    @*<script src="@Url.Content("~/bower_components/jquery/dist/jquery.min.js")"></script>*@
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>
    

</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        @Html.Action("Index", "Navbar")
        
        <div id="page-wrapper">
            @RenderBody()          
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- Custom Theme JavaScript -->
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        //$(document).ready(function () {
        //    $('#dataTables-example').DataTable({
        //        responsive: true
        //    });
        //});
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>

IOCProjectMVC/trunk/IOCProjectMVC/IOCProjectMVC/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>CCLME Data Analytic Viewer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- DataTables CSS -->
    <link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <!-- DataTables Responsive CSS -->
    <link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/bower_components/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />

    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/bower_components/jquery/dist/jquery.min.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>

</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        
        
        <div id="login_principal" class="container-fluid">
            @RenderBody()
        </div>       
       
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
         
    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/raphael/raphael-min.js")"></script>
 
    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>

    <!-- Custom Theme JavaScript -->
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
    <script>
        height = ((this.window.innerHeight > 0) ? this.window.innerHeight : this.screen.height) - 1;

        $("#login_principal").css("min-height", (height) + "px");
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

IOCProjectMVC/trunk/IOCProjectMVC/IOCProjectMVC/Views/Shared/_Navbar.cshtml
@model IEnumerable<IOCProjectMVC.Models.Navbar>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div id="imgnavbar" class="navbar-header">
        @*<a class="navbar-brand" href="#" onclick="closeleftnavbar()">
            <p id="imgclosenavbar" class="fa fa-angle-double-left"></p>
        </a>
        <a class="navbar-brand" href="http://www.aecid.es/ES" target="_blank">
            <img src="~/Img/Gob_CE.png" id="celogo" />
        </a>
        <a class="navbar-brand" href="http://ioc-unesco.org/" target="_blank">
            <img src="~/Img/UNESCO-IOC.png" />
        </a>
        <a class="navbar-brand" href="http://www.ieo.es/" target="_blank">
            <img src="~/Img/LogoIEO.png" />
        </a>*@
        @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>*@
        @Html.ActionLink("CCLME ECO-GIS VIEWER", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-left" id="topNavBarleft">
        <li><a href="#" onclick="showhideLegend()">Legend</a></li>
        <li id="dropdownindexmap" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="#" onclick="showhidePanel('Geodesic_Panel')">Geodesic Tools</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
            </ul>
        </li>
        <li><a id="ClearButton" href="#" onclick="clearGraphics()">Clear</a></li>
        <li><a id="ActionPanelButton" href="#" onclick="ShowHideActionPanel()">Action Panel</a></li>
    </ul>

    <ul class="nav navbar-top-links navbar-right">
        @*<li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-messages">
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>*@
            <!-- /.dropdown-messages -->
        @*</li>*@
        <!-- /.dropdown -->
        @*<li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 1</strong>
                                <span class="pull-right text-muted">40% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    <span class="sr-only">40% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 2</strong>
                                <span class="pull-right text-muted">20% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    <span class="sr-only">20% Complete</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 3</strong>
                                <span class="pull-right text-muted">60% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    <span class="sr-only">60% Complete (warning)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 4</strong>
                                <span class="pull-right text-muted">80% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (danger)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Tasks</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>*@
            <!-- /.dropdown-tasks -->
        @*</li>*@
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="modal" data-target="#modalContact">
                <i class="fa fa-envelope fa-fw"></i>
            </a>
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                    @Html.ActionLink("Log out", "LogOff", "AccountManager", null, new { @class = "fa fa-sign-out fa-fw" })
                    
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </li>
                @foreach (var item in Model)
{
    if (item.isParent == false && item.parentId == 0)
    {
        <li><a href="@Url.Action(item.action, item.controller)"><i class="@item.imageClass"></i> @item.nameOption</a></li>
    }
    else
    {
        if (item.isParent == true)
        {
                            <li>
                                <a href="#"><i class="@item.imageClass"></i> @item.nameOption<span class="fa arrow"></span></a>                          
                                <ul class="nav nav-second-level">
                                    @foreach (var child in Model.Where(p => p.parentId == item.Id))
                                    {
                                        if (child.controller == null)
                                        {
                                            <li><a href="#">@child.nameOption</a></li>
                                        }
                                        else
                                        {
                                            <li><a href="@Url.Action(child.action, child.controller)">@child.nameOption</a></li>
                                        }
                                    }
                                </ul>
                            </li>
                        }
                    }
                }
            </ul>

            <!-- /Logos -->
            <div id="divlogos">
                <a href="http://ioc-unesco.org/" target="_blank">
                    <img class="imglogos" src="~/Img/UNESCO-IOC.png" />
                </a>
                <a href="http://www.ieo.es/" target="_blank">
                    <img class="imglogos" src="~/Img/LogoIEO.png" />
                </a>
                <a href="http://www.aecid.es/ES" target="_blank">
                    <img class="imglogos" src="~/Img/Gob_CE.png" id="celogo" />
                </a>
            </div>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

<!-- Modal -->
<div class="modal fade" id="modalContact" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">The project</h4>
            </div>
            <div class="modal-body">
                <p>The CCLME Data Analytic Viewer is an IOC-UNESCO tool, hosted by the IEO in their servers.</p>
                </br>
                <p>IOC-UNESCO</p>
                <p>7 Place Fontenoy</p>
                <p>75732 Paris cedex 15</p>
                <p>France</p>
                </br>
                <p>Project responsible: Dr Luis Valdes, Head of Ocean Science Section</p>
                <p><a href="mailto:jl.valdes@unesco.org">jl.valdes@unesco.org</a></p>
                </br>
                <p>For questions about the website applications or investigate how to contribute data to CCLME Data Analytic Viewer, email to:</p>
                <p><a href="mailto:lmagudo@gmail.com">lmagudo@gmail.com</a></p>
                </br>
                <p>For questions about the data server and problems accessing the data, email to:</p>
                <p><a href="mailto:lmagudo@gmail.com">lmagudo@gmail.com</a></p>
            </div>
        </div>
    </div>
</div>